export const CHECKIN_COPY = {
  title: (date: string) => `Check in \u00b7 ${date}`,
  subtitle: 'Only mood is required.',
  moodQ: 'How are you today?',
  meetingQOptional: 'Meeting today? (optional)',
  noteQ: 'A note? (optional)',
  noteHelperShared: 'Shared with your sponsor — part of your check-in.',
  noteHelperPrivate: 'Private to you — not shared.',
  save: 'Save check-in',
  update: 'Update check-in',
  saving: 'Saving...',
  updating: 'Updating...',
  customLabel: '+ Custom meeting',
  differentLabel: '+ Different meeting',
  noMeeting: 'No meeting today',
  usualBadge: 'usual',
  personalBadge: 'personal',
  // Phase R additions - entry-first meeting surface
  meetingEntryLabel: 'What meeting did you attend?',
  meetingEntryPlaceholder: 'Type a meeting name...',
  savedMeetingsLabel: 'Your saved meetings',
  noSavedMeetingsHint: "Add it once - we'll have it ready next time.",
  saveForNextTime: '+ Save this meeting for next time',
  addMeetingLabel: '+ Add a meeting',
} as const
